### ISSUE TITLE
Typo in GPS sensor example sketch

### ISSUE THREAD

**Issue by MartinHjelmare** [mysensors/MySensorsArduinoExamples#18]
This sketch has a function `present` instead of `presentation`, so nothing is presented during start of the device.

https://github.com/mysensors/MySensorsArduinoExamples/blob/master/examples/GPSSensor/GPSSensor.ino

**Comment by henrikekblad** [comment]
Opps, 

could you fix?

**Comment by MartinHjelmare** [comment]
No problem. PR ready.
