### ISSUE TITLE
Use private member in temperature example

### ISSUE THREAD

**Issue by Ducatel** [mysensors/MySensorsArduinoExamples#20]
Hi everybody,

In [Dallas temperature example](https://github.com/mysensors/MySensorsArduinoExamples/blob/master/examples/DallasTemperatureSensor/DallasTemperatureSensor.ino#L85) there is a bad call to private member
```
error: 'int16_t DallasTemperature::millisToWaitForConversion(uint8_t)' is private
```

[According to the Dallas library](https://github.com/milesburton/Arduino-Temperature-Control-Library/blob/master/DallasTemperature.h#L254).

So this error should be fixed in example or in the library ?

Thanks ;)

**Comment by henrikekblad** [comment]
Nope, it is in the public section:
https://github.com/mysensors/MySensorsArduinoExamples/blob/master/libraries/DallasTemperature/DallasTemperature.h#L121

**Comment by Ducatel** [comment]
oh, you don't use the official version of the library.
Why ? What is the reason for that ?
So this example cannot be use in a real code ?

Quick view of my arduino/Mysensor builder script
```sh
arduino --install-library "MySensors"
arduino --install-library "OneWire"
arduino --install-library "DallasTemperature" # This line not install the "custom" version 
.......

arduino --verify --board arduino:avr:uno  src/temp.ino # fail because of the private call
```

This is not the good way to build a MySensor project ?

**Comment by henrikekblad** [comment]
Well, it seems to have been needed by @roboprint back in 2015. Guess he found it useful in the example. 

https://github.com/mysensors/MySensors/commit/e47e596075282b122ac5d266ec6ad5c60ca8c978

**Comment by Ducatel** [comment]
Ok so it's usefull for us.
So I will make a PR to the official Dallas lib ;)

**Comment by henrikekblad** [comment]
👍 

When it is in, you can remove the Dallas library from this repo.

**Comment by roboprint** [comment]
This is used for non-blocking temperature reading. You cannot receive messages from MySensors, send messages or do other tasks during 750 millisecond thread-blocking temperature conversion. Blocking calls isn't very good solution for MySensors nodes providing other interactive functions to users (light switch as example).

Right way is do PR into Dallas lib, but as far as I remember in those days Dallas library was bundled with MySensors.

**Comment by Kolbi** [comment]
I downloaded the library from the official github repo but I'm still having the same issue?

**Comment by Kolbi** [comment]
@Ducatel your repo is working, Maybe you can update/fix the official repo again?
