### ISSUE TITLE
The DHT library forked from original source, documentation needs updated.

### ISSUE THREAD

**Issue by cravecode** [mysensors/MySensorsArduinoExamples#4]
In PR #1, the DHT library was altered (see commit: e97ae9e2df18e29cb9dc3c4f5945795b7baca6a9). 

The documentation for the DHT library in the README.md file says to download and install in your libraries. The suggested download location refers to the old unmodified version from the original author's [GH DHT repo](https://github.com/markruys/arduino-DHT).

What is the suggested protocol for using contributed and potentially forked libraries that are in this repo's `/libraries` directory?

I don't mind creating a PR to update the documentation. I just want to understand what the correct procedure regarding contributed libraries should be.

**Comment by henrikekblad** [comment]
You could just copy the library to your Arduino IDEs library folder. Find the location through the preferences menu.

**Comment by cravecode** [comment]
I have it worked out. I'm more concerned about other people not having documentation when they run into the same issue.
