### ISSUE TITLE
Always fail sending 

### ISSUE THREAD

**Issue by ilbordi** [mysensors/MySensorsArduinoExamples#44]
Hi, I can't send any messages to my phone because it always enters the "Failed" part of this     

`    message.encode(ndefBuf);
    if (0 >= nfc.write(ndefBuf, messageSize)) {
        Serial.println("Failed");
    } else {
       Serial.println("Success");
    }
`
How can I fix?

**Comment by mfalkvidd** [comment]
@ilbordi could you explain which MySensors example is this related to?

**Comment by ilbordi** [comment]
@mfalkvidd hi I have fixed the problem, it was related to the wires not to the code
Sorry

**Comment by mfalkvidd** [comment]
Great! Thanks for reporting back.
