### ISSUE TITLE
HTTP_GET

### ISSUE THREAD

**Issue by Finneycesd123** [mysensors/MySensorsArduinoExamples#45]
boolean Adafruit_FONA_3G::HTTP_GET_start(char *ipaddr, char *path, uint16_t port
				      uint16_t *status, uint16_t *datalen)

Please help in writing a sample for this. Also this part is in comment state. is there any issue with the library

**Comment by mfalkvidd** [comment]
@Finneycesd123 you'll probably get a better response if you ask in the original library. https://github.com/adafruit/Adafruit_FONA_Library
