### ISSUE TITLE
Node is not going to Sleep with this Sketch.

### ISSUE THREAD

**Issue by Fl0ca** [mysensors/MySensorsArduinoExamples#9]
MySensorsArduinoExamples/examples/DallasTemperatureSensor/DallasTemperatureSensor.ino

It constantly consumes between 17-18mA, without going to sleep. Sending works with the defined milliseconds, but between Sending it is not sleeping.

**Comment by mfalkvidd** [comment]
Which Arduino/mcu are you using? How is it powered?
Could you post the serial debug output from the node (helps a lot when troubleshooting).

The battery powering instructions at https://www.mysensors.org/build/battery might give a clue to what is wrong.

**Comment by mfalkvidd** [comment]
Closing, as troubleshooting without additional information is very hard. Feel free to reopen with more information.
